### Home
GET  http://localhost:3001/api

### Get All
GET http://localhost:3001/api/contacts

### Create One
POST http://localhost:3001/api/contacts
Content-Type: application/json

{ 
    "name":"علی محمدی" , 
    "number": "0936456123"
}
### Edit One
PUT  http://localhost:3001/api/contacts
Content-Type: application/json

{
	"id": 3,
	"name": "pou142sddaaaaayaan",
	"number": "648"
}
### Delete One
DELETE  http://localhost:3001/api/contacts/4